# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='ssn',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
