# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 15:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20161028_0608'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='api_ref',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='party',
            name='image_url',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='party',
            name='ref',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='party',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Búið til af'),
        ),
        migrations.AlterField(
            model_name='party',
            name='dt_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Búið til'),
        ),
        migrations.AlterField(
            model_name='party',
            name='dt_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Breytt'),
        ),
        migrations.AlterField(
            model_name='party',
            name='modified_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Breytt af'),
        ),
        migrations.AlterField(
            model_name='person',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Búið til af'),
        ),
        migrations.AlterField(
            model_name='person',
            name='dt_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Búið til'),
        ),
        migrations.AlterField(
            model_name='person',
            name='dt_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Breytt'),
        ),
        migrations.AlterField(
            model_name='person',
            name='modified_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Breytt af'),
        ),
        migrations.AlterField(
            model_name='promise',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Búið til af'),
        ),
        migrations.AlterField(
            model_name='promise',
            name='dt_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Búið til'),
        ),
        migrations.AlterField(
            model_name='promise',
            name='dt_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Breytt'),
        ),
        migrations.AlterField(
            model_name='promise',
            name='modified_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Breytt af'),
        ),
        migrations.AlterField(
            model_name='promisesource',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Búið til af'),
        ),
        migrations.AlterField(
            model_name='promisesource',
            name='dt_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Búið til'),
        ),
        migrations.AlterField(
            model_name='promisesource',
            name='dt_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Breytt'),
        ),
        migrations.AlterField(
            model_name='promisesource',
            name='modified_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Breytt af'),
        ),
        migrations.AlterField(
            model_name='source',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Búið til af'),
        ),
        migrations.AlterField(
            model_name='source',
            name='dt_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Búið til'),
        ),
        migrations.AlterField(
            model_name='source',
            name='dt_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Breytt'),
        ),
        migrations.AlterField(
            model_name='source',
            name='modified_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Breytt af'),
        ),
    ]
