# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20161028_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='api_ref',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='person',
            name='image_url',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='person',
            name='is_mp',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='person',
            name='is_substitute',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='ref',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='person',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
