# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 21:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_auto_20161028_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='Búið til')),
                ('dt_modified', models.DateTimeField(auto_now=True, verbose_name='Breytt')),
                ('title', models.CharField(max_length=255)),
                ('detail', models.TextField(blank=True)),
                ('dt_claimed', models.DateTimeField(blank=True, null=True)),
                ('truthfulness', models.CharField(choices=[('True', 'Dagsatt'), ('Mostly True', 'Næstum því satt'), ('Half True', 'Hálfsannleikur'), ('Mostly False', 'Aðallega ósatt'), ('False', 'Haugalýgi')], max_length=50, verbose_name='Sannleiksgildi')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Búið til af')),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Breytt af')),
            ],
            options={
                'verbose_name_plural': 'Fullyrðingar',
                'verbose_name': 'Fullyrðing',
            },
        ),
        migrations.CreateModel(
            name='ClaimSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='Búið til')),
                ('dt_modified', models.DateTimeField(auto_now=True, verbose_name='Breytt')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField(blank=True, max_length=255)),
                ('detail', models.TextField(blank=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='main.Claim')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Búið til af')),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Breytt af')),
            ],
            options={
                'verbose_name_plural': 'Heimildir',
                'verbose_name': 'Heimild',
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='party',
            options={'verbose_name': 'Flokkur', 'verbose_name_plural': 'Flokkar'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Aðili', 'verbose_name_plural': 'Aðilar'},
        ),
        migrations.AlterModelOptions(
            name='promise',
            options={'verbose_name': 'Loforð', 'verbose_name_plural': 'Loforð'},
        ),
        migrations.AlterModelOptions(
            name='promisesource',
            options={'verbose_name': 'Heimild', 'verbose_name_plural': 'Heimildir'},
        ),
        migrations.AlterModelOptions(
            name='source',
            options={'verbose_name': 'Miðill', 'verbose_name_plural': 'Miðlar'},
        ),
        migrations.AlterField(
            model_name='party',
            name='about',
            field=models.TextField(blank=True, verbose_name='Um flokkinn'),
        ),
        migrations.AlterField(
            model_name='party',
            name='api_ref',
            field=models.URLField(blank=True, max_length=255, verbose_name='API tilvísun'),
        ),
        migrations.AlterField(
            model_name='party',
            name='ident',
            field=models.CharField(max_length=10, verbose_name='Stafur'),
        ),
        migrations.AlterField(
            model_name='party',
            name='image_url',
            field=models.URLField(blank=True, max_length=255, verbose_name='Mynd'),
        ),
        migrations.AlterField(
            model_name='party',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nafn'),
        ),
        migrations.AlterField(
            model_name='party',
            name='ref',
            field=models.URLField(blank=True, max_length=255, verbose_name='Tilvísun'),
        ),
        migrations.AlterField(
            model_name='party',
            name='website',
            field=models.URLField(blank=True, max_length=255, verbose_name='Vefur'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nafn'),
        ),
        migrations.AlterField(
            model_name='promise',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promises', to='main.Person'),
        ),
        migrations.AddField(
            model_name='claimsource',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Source'),
        ),
        migrations.AddField(
            model_name='claim',
            name='parties_accused',
            field=models.ManyToManyField(related_name='accused_by_claims', to='main.Party'),
        ),
        migrations.AddField(
            model_name='claim',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='main.Party'),
        ),
        migrations.AddField(
            model_name='claim',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='main.Person'),
        ),
        migrations.AddField(
            model_name='claim',
            name='persons_accused',
            field=models.ManyToManyField(related_name='accused_by_claims', to='main.Person'),
        ),
    ]
