# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 13:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20161029_0243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='ssn',
        ),
    ]
